{% set name = "outdated" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d92921a3d77bc56a6d39c0af321aad44b223906ebb6e8139996d26116baec573

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - littleutils
    - requests

test:
  imports:
    - outdated

about:
  home: https://github.com/alexmojaki/outdated
  license: MIT
  license_family: MIT
  # PR to include license file upstream: https://github.com/alexmojaki/outdated/pull/4
  license_file: LICENSE
  summary: Check if a version of a PyPI package is outdated
  description: |
    This is a mini-library which, given a package name and a version,
    checks if it's the latest version available on PyPI.

extra:
  recipe-maintainers:
    - hoechenberger
